/** @type {import('tailwindcss').Config} */
const v = (name) => `var(--${name})`;

// Tokeny z makiety (1:1 ze zmiennymi w global.css): bg-brand-deep, text-ink-3, bg-warn-bg...
const tokens = {
  chrome: v("chrome"),
  brand: v("brand"),
  "brand-ink": v("brand-ink"),
  "brand-deep": v("brand-deep"),
  "brand-deep-ink": v("brand-deep-ink"),
  "brand-soft": v("brand-soft"),
  "brand-hover": v("brand-hover"),
  accent: v("accent"),
  info: v("info"),
  violet: v("violet"),
  "on-brand": v("on-brand"),
  "on-brand-soft": v("on-brand-soft"),
  "on-brand-dim": v("on-brand-dim"),
  surface: v("surface"),
  screen: v("screen"),
  desk: v("desk"),
  field: v("field"),
  "bg-1": v("bg-1"),
  "bg-2": v("bg-2"),
  "tint-1": v("tint-1"),
  "tint-2": v("tint-2"),
  "tint-3": v("tint-3"),
  "tint-4": v("tint-4"),
  "ink-1": v("ink-1"),
  "ink-2": v("ink-2"),
  "ink-3": v("ink-3"),
  "ink-4": v("ink-4"),
  "ink-5": v("ink-5"),
  "ink-6": v("ink-6"),
  "ink-7": v("ink-7"),
  "ink-8": v("ink-8"),
  "line-1": v("line-1"),
  "line-2": v("line-2"),
  "line-3": v("line-3"),
  "line-4": v("line-4"),
  "line-5": v("line-5"),
  danger: v("danger"),
  "danger-solid": v("danger-solid"),
  "danger-bg": v("danger-bg"),
  "danger-line": v("danger-line"),
  "danger-ink": v("danger-ink"),
  warn: v("warn"),
  "warn-solid": v("warn-solid"),
  "warn-bg": v("warn-bg"),
  "warn-bg-soft": v("warn-bg-soft"),
  "warn-line": v("warn-line"),
  "warn-line-strong": v("warn-line-strong"),
  "warn-ink": v("warn-ink"),
  "warn-ink-strong": v("warn-ink-strong"),
  ok: v("ok"),
  "ok-solid": v("ok-solid"),
  "ok-bg": v("ok-bg"),
  "ok-bg-soft": v("ok-bg-soft"),
  "ok-line": v("ok-line"),
  "ok-ink": v("ok-ink"),
};

// Aliasy semantyczne — wskazują tokeny, nie duplikują wartości.
const semantic = {
  foreground: v("ink-1"),
  "muted-foreground": v("ink-3"),
  primary: v("brand"),
  "primary-foreground": v("on-brand"),
  link: v("brand-ink"),
  border: v("line-2"),
  "border-strong": v("line-5"),
  input: v("field"),
  "input-border": v("ink-5"),
  placeholder: v("ink-5"),
  destructive: v("danger"),
  success: v("ok"),
  warning: v("warn-ink"),
  disabled: v("line-4"),
  "disabled-foreground": v("ink-2"),
};

// Statusy badań: bg-status-<id> text-status-<id>-foreground
const status = {
  "status-planned": v("status-planned-bg"),
  "status-planned-foreground": v("status-planned-fg"),
  "status-scheduled": v("status-scheduled-bg"),
  "status-scheduled-foreground": v("status-scheduled-fg"),
  "status-in-progress": v("status-in-progress-bg"),
  "status-in-progress-foreground": v("status-in-progress-fg"),
  "status-awaiting-result": v("status-awaiting-result-bg"),
  "status-awaiting-result-foreground": v("status-awaiting-result-fg"),
  "status-closed": v("status-closed-bg"),
  "status-closed-foreground": v("status-closed-fg"),
  "status-urgent": v("status-urgent-bg"),
  "status-urgent-foreground": v("status-urgent-fg"),
};

module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: { ...tokens, ...semantic, ...status },
    },
  },
  plugins: [],
};
